dmu-most/vblog-client

src/Router.tsx
src/components/common/PostCard.tsx
src/pages/MainPage.tsx

`feat/Main/#007` -> `dev`
- /경로 생성했습니다.
- 없습니다.

feat: Mainpage 생성 및 /경로 생성

---

src/components/main/BannerComponent.tsx
src/components/main/CardComponent.tsx
src/components/main/IntroComponent.tsx
src/data/dummyData.ts
src/pages/DetailPage.tsx
src/pages/MainPage.tsx

`feat/refactor` -> `dev`
- 파일명 대문자 -> 소문자 변경

rename: 파일명 대문자->소문자 변경

---

src/components/main/CardComponent.tsx
src/pages/OauthCallbackPage.tsx

- 메인 페이지 카드 스크롤 버그 수정
- 쿼리 param 오타 수정

fix: 메인 페이지 카드 스크롤 버그 수정

---

src/api/auth/login.ts
src/api/auth/signUp.ts
src/api/auth/token.ts
src/api/axiosInstance.ts
src/api/myInfo.ts
src/components/header/MyInfoDropDowm.tsx
src/components/header/RightHeader.tsx
src/components/my-info/ProfileDescription.tsx
src/types/auth/token.ts
src/types/myInfo.ts

- 헤더 드롭다운 버튼 over되는 버그 수정
- 헤더 유저 드롭다운 blur 처리
- 토큰이 필요한지 확인한 후, 각 분기에 맞게 사용할 수 있도록 구현
- 회원정보 조회 API 연결
axios instance로 요청할 때 다음과 같이 추가
**1. 토큰이 필요하지 않을 경우**
```ts
headers: {
'No-Auth': true,
},
```
**2. 액세스 토큰만 필요할 경우**
```ts
headers: {
'Only-Authorization': true,
},
```
**3. 리프레시 토큰만 필요할 경우**
```ts
headers: {
'Only-Refresh': true,
},

api: 회원정보 조회 API 연결 및 axios instance 수정

---

src/layout/Footer.tsx
src/layout/Header.tsx
src/layout/Main.tsx
src/styles/GlobalStyles.ts
src/styles/theme.ts

- 모바일 쿼리 수정
- 블로그 배경색 수정
- 로그인/회원가입 페이지 색상 고정
- 쿼리 및 콘텐츠 최대 너비 변수 이름 변경!

feat: 콘텐츠 최대 너비 및 모바일 쿼리 추가

---

src/components/header/MyInfoDropDown.tsx
src/components/header/RightHeader.tsx
src/components/my-info/ProfileDescription.tsx
src/components/sign/LoginHeader.tsx
src/layout/Footer.tsx
src/layout/Header.tsx
src/layout/Main.tsx
src/pages/OauthCallbackPage.tsx
src/pages/SignUpPage.tsx
src/types/auth/login.ts

`feat/signup/#11` -> `dev`
- OAuth 소셜 로그인 기능 추가
- 모바일 디바이스에서 드롭다운 숨겨지는 버그 수정
- dowm -> down 파일 이름 오타 수정
- padding 값 잘못 준 부분 수정
- 마이페이지 프로필 이미지 둥글게 수정

feat: OAuth 소셜 로그인 기능 추가

---

src/components/common/PostCard.tsx
src/components/main/BannerComponent.tsx
src/components/main/CardComponent.tsx
src/components/main/IntroComponent.tsx
src/pages/MainPage.tsx

`feat/fixmain/#026` -> `dev`
- main font 크기 수정
- card CSS 수정 (미완성)
- card CSS 최종 수정 후 머지 부탁드려요

feat: mainpage layout 수정

---

package-lock.json
package.json
src/components/Category/CategoryDropdown.tsx
src/components/Category/CategotyCardComponent.tsx
src/components/common/Hashtag.tsx
src/components/common/PostCard.tsx
src/components/common/ReviewForm.tsx
src/components/detail/CommandComponent.tsx
src/components/detail/ContentComonent.tsx
src/components/detail/ReviewComponent.tsx
src/data/dummyData.ts
src/pages/CategoryPage.tsx
src/types/detail/review.ts
src/types/detail/vblog.ts
src/types/main/list.ts

`feat/review_jh/#028` -> `dev`
- 카테고리 최신순/인기순 api 서버 연결
- 찜 UI 추가
- 카테고리 너비,여백 수정
- review type 추가
- review dummydata 추가
- react-route-dom 최신화 시켜서 npm install 부탁드려요!

api: 카테고리 최신순/인기순 api 서버 연결 , feat: 찜 UI , review dummydata 추가

---

README.md
src/api/axiosInstance.ts
src/api/myInfo.ts
src/components/my-info/MyInfoContent.tsx
src/components/my-info/ProfileDescription.tsx
src/components/my-info/ProfileImageEdit.tsx
src/components/my-info/ProfileNameEdit.tsx
src/components/my-info/SocialIcons.tsx
src/components/my-info/UserProfileUpdate.tsx
src/pages/MyPage.tsx
src/types/myInfo.ts

`feat/signup/#11` -> `dev`
- 마이페이지 회원정보 수정 레이아웃 구현
- 소셜 로그인 컴포넌트 분리
- 마이페이지 CSS 수정
- axios 인터셉터 수정

feat: 마이페이지 회원정보 수정 레이아웃 구현

---

src/api/axiosInstance.ts
src/api/myInfo.ts
src/components/header/RightHeader.tsx
src/components/my-info/ProfileDescription.tsx
src/components/my-info/ProfileImageEdit.tsx
src/components/my-info/UserProfileUpdate.tsx
src/types/myInfo.ts

- 데이터 정보가 없는 회원이 로그인 시 토큰 재확인 요청하는 버그 수정
- store import 위치 수정
- 마이페이지 회원정보 수정 기능 구현

feat: 마이페이지 회원정보 수정 기능 구현

---

src/api/my-info/content.ts
src/components/my-info/MyInfoContent.tsx
src/components/my-info/MyRecentItem.tsx
src/components/my-info/MyRecentList.tsx
src/components/my-info/MyReviewItem.tsx
src/components/my-info/MyReviewList.tsx
src/components/my-info/ReviewPagination.tsx
src/types/my-info/content.ts

- 브이로그/블로그 최근 기록 레이아웃 구현
- 브이로그/블로그 리뷰 레이아웃 구현

브이로그/블로그 최근 기록 및 리뷰 레이아웃 구현

---

package-lock.json
package.json
src/api/detail/review.ts
src/api/main/vblogList.ts
src/components/detail/ReviewComponent.tsx
src/components/detail/modal/RatingModal.tsx
src/components/main/CardComponent.tsx
src/components/main/UserCardComponent.tsx
src/pages/MainPage.tsx
src/types/detail/review.ts

`feat/usercard_jh/#033` -> `dev`
- 사용자 알고리즘 api 서버 연결
- 리뷰 작성 api 서버 연결
- banner api instance로 수정
- 화살표 캐러셀 사용
- 에러는 없지만 현재 두가지 다 수정 좀 더 필요
- 캐러셀 사용으로 npm install 필요

api: 리뷰 작성 , 사용자 알고리즘 api 서버 연결(수정 필요)

---

package-lock.json
package.json
src/api/detail/review.ts
src/api/main/vblogList.ts
src/components/detail/ReviewComponent.tsx
src/components/detail/modal/RatingModal.tsx
src/components/main/CardComponent.tsx
src/components/main/UserCardComponent.tsx
src/pages/MainPage.tsx
src/types/detail/review.ts

`feat/usercard_jh/#034` -> `dev`
- 사용자 알고리즘 api 서버 연결
- 리뷰 작성 api 서버 연결
- banner api instance로 수정
- 화살표 캐러셀 사용
- 에러는 없지만 현재 두가지 다 수정 좀 더 필요
- 캐러셀 사용으로 npm install 필요

api: 리뷰 작성 ,  사용자 알고리즘 api 서버 연결 [dev]

---

src/api/detail/review.ts
src/components/common/ReviewForm.tsx
src/components/detail/ReviewComponent.tsx
src/components/detail/modal/RatingModal.tsx
src/types/detail/review.ts

`feat/review04_jh/#035` -> `dev`
- 리뷰 css 수정
- 리뷰 작성 api 수정 완료
- 리뷰 작성 완료 시 refresh 함수 추가
- X

Review04 jh

---

src/api/detail/content.ts
src/api/detail/index.ts
src/api/my-info/content.ts
src/components/my-info/InterestList.tsx
src/components/my-info/MyInfoContent.tsx
src/components/my-info/MyRecentItem.tsx
src/components/my-info/MyRecentList.tsx
src/components/my-info/MyReviewItem.tsx
src/components/my-info/MyReviewList.tsx
src/components/my-info/MyScrapList.tsx
src/components/my-info/ReviewPagination.tsx
src/components/my-info/UserProfileUpdate.tsx
src/components/sign/LoginForm.tsx
src/pages/DetailPage.tsx
src/types/detail/index.ts
src/types/detail/vblog.ts
src/types/index.ts
src/types/my-info/content.ts

- 최근목록 post 기능 추가
- 로그인 시 카테고리 여부 넘어오는 부분 제외하고, 회원 정보 전역 상태 저장
- 마이페이지 최근목록 이미지 요소가 오버되는 버그 수정
- 스크랩 카테고리 추가 레이아웃 구현
- 카테고리 수정 레이아웃 구현

feat: 마이페이지 카테고리 레이아웃 구현 및 버그 수정

---

src/api/detail/index.ts
src/api/detail/vblogContent.ts
src/api/detail/vblogInfo.ts
src/api/main/index.ts
src/api/main/vblogList.ts
src/components/common/BannerTag.tsx
src/components/common/ReviewForm.tsx
src/components/detail/CommandComponent.tsx
src/components/detail/ContentComonent.tsx
src/components/detail/LikeDisLikeButton.tsx
src/components/detail/ReviewComponent.tsx
src/components/detail/modal/ScrapModal.tsx
src/components/main/CardComponent.tsx
src/pages/DetailPage.tsx
src/pages/MainPage.tsx
src/types/detail/vblog.ts

`feat/heart_jh/#036` -> `dev`
- Carousel css 수정
- deatailContent 조회 인스턴스로 수정
- 사용자 알고리즘은 보류로 주석처리 
- 좋아요,싫어요,스크랩 UI 수정
- 스크랩 모달 UI 구성
- detailPage , detail api에서 충돌나서 조합해서 push
- detailPage , detail api에서 충돌나서 조합했는데 오류나면 저 불러주세요!
- ScrapModal.tsx  import 시 다음과 같이 추가
```ts
// import 방식
// Component
import ScrapModal from "./modal/ScrapModal";
...
// hook 추가
const [isModalOpen, setIsModalOpen] = useState(false);
// 해당 컨테이너의 선언
<ScrapModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} />
```

feat: 좋아요,싫어요,스크랩 UI 수정 , 스크랩 모달 UI 구성

---

src/components/my-info/MyInfoContent.tsx
src/components/my-info/MyReviewList.tsx

style: 마이페이지 ul 여백 수정

---

src/api/auth/token.ts
src/api/axiosInstance.ts
src/api/detail/content.ts
src/api/detail/review.ts
src/api/detail/vblogInfo.ts
src/api/main/vblogList.ts
src/api/my-info/content.ts
src/api/my-info/member.ts

- axios interceptors에서 헤더 기본 값을 액세스 토큰만 요청하도록 수정
1. 액세스 토큰만 요청할 경우
```tsx
헤더 요청 없음
``` 
2. 리프레시 토큰만 요청할 경우
```tsx
headers: {
'Only-Refresh': true,
},
```
3. 리프레시 & 액세스 토큰 두개 다 요청할 경우
```tsx
headers: {
'Both-Tokens': true,
},
```

fix: axios interceptors에서 헤더에 액세스 토큰만 요청하는 걸 기본으로 지정

---

src/api/main/vblogList.ts
src/components/Category/CategotyCardComponent.tsx
src/components/common/BannerTag.tsx
src/components/common/Hashtag.tsx
src/components/detail/CommandComponent.tsx
src/components/main/BannerComponent.tsx
src/components/main/CardComponent.tsx
src/data/dummyData.ts
src/layout/Main.tsx
src/layout/index.tsx
src/pages/DetailPage.tsx
src/pages/MainPage.tsx
src/styles/GlobalStyles.ts
src/types/main/list.ts

`feat/bannertag_jh/#040` -> `dev`
- main, detaill loader 적용
- bannertag 조회 api 서버 연결
- 카테고리 반응형 css 수정
- 검색 완료되면 bannertag -> 검색으로 넘어가게 할 예정

api: bannertag 조회 api 서버 연결

---

src/api/my-info/content.ts
src/components/common/BannerTag.tsx
src/components/detail/LikeDisLikeButton.tsx
src/components/detail/modal/ScrapModal.tsx

`feat/bannertag02_jh/#041` -> `dev`
- bannertag 반응형 수정
- 폴더 조회 api 서버 연결
- 새 폴더 만들기 api 서버 연결
- 스크랩 저장하기는 상의 후 서버 연결

api: 스크랩 모달 폴더 조회, 새 폴더 만들기 api 서버 연결

---

src/api/my-info/content.ts
src/components/detail/ContentComonent.tsx
src/components/detail/LikeDisLikeButton.tsx
src/components/detail/modal/ScrapModal.tsx
src/store/useLikeDislikeStore.ts
src/types/my-info/content.ts

`feat/scrap03_jh/#042` -> `dev`
- 스크랩 저장 api 서버 연결
- 좋아요/싫어요 상태 수정(추후 수정 더 필요)
- X

api: 스크랩 저장 api 서버 연결 , 좋아요/싫어요 상태 수정

---

src/api/main/vblogList.ts
src/api/my-info/content.ts
src/api/post/post.ts
src/components/common/BannerTag.tsx
src/components/detail/modal/ScrapModal.tsx
src/components/main/BannerComponent.tsx

`feat/scrap04_jh/#043` -> `dev`
- scrap api 수정으로 인한 풀뤼퀘
-

fix: scrap api 수정

---

src/api/my-info/content.ts
src/components/main/BannerComponent.tsx
src/components/my-info/MyScrapItem.tsx
src/components/my-info/MyScrapList.tsx
src/components/my-info/ScrapFolderList.tsx
src/pages/DetailPage.tsx
src/types/my-info/content.ts

- 마이페이지 스크랩 조회
- 스크랩 0개일 때 버그 수정
- 배너 이미지 깨지는 현상 수정

feat: 마이페이지 스크랩 API 연결 및 구현
